version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
    - run:
        command: yarn cy:install
        command: yarn cy:run

workflows:
  example-workflow:
    jobs:
      - example-job
